[opener]
edit = [
	{ run = 'nvim %*', block = true, desc = "nvim", for = "windows" },
]

[open]
prepend_rules = [
    { url = ".txt", use = "edit" },{ url = ".md", use = "edit" },
    { url = ".toml", use = "edit" },{ url = ".lua", use = "edit" },
    { url = ".json", use = "edit" },{ url = ".yaml", use = "edit" },
    { url = ".yml", use = "edit" },{ url = ".conf", use = "edit" },
    { url = ".ini", use = "edit" },{ url = ".csv", use = "edit" },
    { url = ".log", use = "edit" },{ mime = "text/", use = "edit" },
]
